
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - car-service
      - booking-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env

  car-service:
    build: ./car-service
    ports:
      - "3002:3002"
    env_file:
      - ./car-service/.env

  booking-service:
    build: ./booking-service
    ports:
      - "3003:3003"
    env_file:
      - ./booking-service/.env
